// resources/js/lang.js - Pusat teks UI Bahasa Indonesia
export const lang = {
    app: {
        name: 'SIPELA',
        fullName: 'Sistem Pelaporan Lansia Puskesmas Payolansek',
        city: 'Kota Payakumbuh',
    },
    nav: {
        home: 'Beranda',
        reports: 'Laporan',
        scan: 'Scan',
        stats: 'Statistik',
        menu: 'Menu',
        logout: 'Keluar',
        profile: 'Profil',
        users: 'Kelola Pengguna',
        kelurahan: 'Kelola Kelurahan',
    },
    auth: {
        loginTitle: 'Masuk ke SIPELA',
        loginSubtitle: 'Puskesmas Payolansek · Pelaporan Lansia',
        email: 'Email',
        emailPlaceholder: 'nama@sipela.test',
        password: 'Kata Sandi',
        passwordPlaceholder: 'Masukkan kata sandi',
        rememberMe: 'Ingat saya di perangkat ini',
        loginButton: 'Masuk',
        loggingIn: 'Memproses...',
        forgotPassword: 'Lupa kata sandi?',
        roleAdmin: 'Administrator',
        rolePetugas: 'Petugas Lansia',
    },
    dashboard: {
        greeting: 'Halo',
        currentReport: 'Laporan Bulan Ini',
        quickActions: 'Aksi Cepat',
        scanReport: 'Scan Laporan',
        manualInput: 'Isi Manual',
        spmCoverage: 'Capaian Standar (>60 th)',
        visitTrends: 'Tren Kunjungan',
        recap: 'Rekapitulasi',
        draft: 'Draft',
        final: 'Final (Terkunci)',
    },
    common: {
        back: 'Kembali',
        save: 'Simpan',
        saving: 'Menyimpan...',
        saved: 'Tersimpan ✓',
        cancel: 'Batal',
        confirm: 'Konfirmasi',
        edit: 'Ubah',
        delete: 'Hapus',
        close: 'Tutup',
        empty: 'Belum ada data',
        error: 'Terjadi kesalahan. Silakan coba lagi.',
        calculatedAutomatically: 'Dihitung otomatis',
    },
};

export default lang;
