// resources/js/lang.js - Pusat teks UI Bahasa Indonesia
export const lang = {
    app: {
        name: 'SIPELA',
        fullName: 'Sistem Pelaporan Lansia Puskesmas Payolansek',
        city: 'Kota Payakumbuh',
    },
    nav: {
        home: 'Beranda',
        reports: 'Laporan',
        scan: 'Scan',
        stats: 'Statistik',
        menu: 'Menu',
        logout: 'Keluar',
        profile: 'Profil',
        users: 'Kelola Pengguna',
        kelurahan: 'Kelola Kelurahan',
    },
    auth: {
        loginTitle: 'Masuk ke SIPELA',
        loginSubtitle: 'Puskesmas Payolansek · Pelaporan Lansia',
        email: 'Email',
        emailPlaceholder: 'nama@sipela.test',
        password: 'Kata Sandi',
        passwordPlaceholder: 'Masukkan kata sandi',
        rememberMe: 'Ingat saya di perangkat ini',
        loginButton: 'Masuk',
        loggingIn: 'Memproses...',
        forgotPassword: 'Lupa kata sandi?',
        roleAdmin: 'Administrator',
        rolePetugas: 'Petugas Lansia',
    },
    dashboard: {
        greeting: 'Halo',
        currentReport: 'Laporan Bulan Ini',
        quickActions: 'Aksi Cepat',
        scanReport: 'Scan Laporan',
        manualInput: 'Isi Manual',
        spmCoverage: 'Capaian Standar (>60 th)',
        visitTrends: 'Tren Kunjungan',
        recap: 'Rekapitulasi',
        draft: 'Draft',
        final: 'Final (Terkunci)',
        notCreated: 'Belum Dibuat',
        kelurahanFilled: 'kelurahan terisi',
    },
    stats: {
        title: 'Statistik & Tren Pelayanan',
        subtitle: 'Visualisasi tren kunjungan bulanan dan capaian SPM lansia',
        filterYear: 'Tahun',
        filterKelurahan: 'Kelurahan',
        allKelurahans: 'Semua Kelurahan (Puskesmas)',
        visitTrendTitle: 'Tren Kunjungan per Bulan',
        visitTrendSubtitle: 'Perbandingan kunjungan dalam gedung, luar gedung, dan total',
        spmChartTitle: 'Lansia Dilayani Sesuai Standar (>60 th)',
        spmChartSubtitle: 'Capaian SPM laki-laki, perempuan, dan persentase terhadap sasaran',
        tableTitle: 'Tabel Data Bulanan',
        tableSubtitle: 'Rincian angka agregat per bulan (terbaca & dapat diakses)',
        month: 'Bulan',
        totalVisits: 'Total Kunjungan',
        inBuilding: 'Dalam Gedung',
        outBuilding: 'Luar Gedung',
        maleAbs: 'Laki-laki (Abs)',
        femaleAbs: 'Perempuan (Abs)',
        spmTotal: 'Total Dilayani',
        spmPct: '% Capaian SPM',
        targetLansia: 'Sasaran Lansia (>60 th)',
        totalAnnualVisits: 'Total Kunjungan Tahun Ini',
        totalAnnualSpm: 'Total Dilayani Sesuai Standar',
        latestSpmPct: 'Capaian SPM Terakhir',
        noDataInYear: 'Belum ada data laporan pada tahun ini.',
        gapNotice: 'Bulan tanpa data tampil sebagai celah grafik.',
    },
    export: {
        title: 'Ekspor Laporan Excel',
        subtitle: 'Unduh laporan format resmi Dinas Kesehatan Kota TA 2026 (.xlsx)',
        selectYear: 'Tahun Pelaporan',
        selectMonth: 'Cakupan Bulan',
        allMonthsOption: 'Semua Bulan (1 Tahun Penuh) — Rekomendasi Format Dinkes',
        downloadButton: 'Unduh Berkas Excel (.xlsx)',
        downloading: 'Menyiapkan berkas...',
        templateNotice: 'Berkas hasil ekspor menggunakan rumus asli template Dinkes (sheet Lap. Kunjungan & Lap. Layanan Lansia) dan dapat langsung diserahkan.',
        summaryBadge: 'Format Baku Dinkes',
    },
    common: {
        back: 'Kembali',
        save: 'Simpan',
        saving: 'Menyimpan...',
        saved: 'Tersimpan ✓',
        cancel: 'Batal',
        confirm: 'Konfirmasi',
        edit: 'Ubah',
        delete: 'Hapus',
        close: 'Tutup',
        empty: 'Belum ada data',
        error: 'Terjadi kesalahan. Silakan coba lagi.',
        calculatedAutomatically: 'Dihitung otomatis',
    },
};

export default lang;
